hydra:
  run:
    dir: outputs/${experiment_name}/${training_cfg.SetupNN.model_name}/${now:%Y-%m-%d_%H-%M-%S}
defaults:
  - ../../configs@_global_.training_cfg: training_v1
  - _self_

# mlflow
path_to_mlflow: mlruns
experiment_name: ???

# pretrained: null
pretrained:
  run_id : 7041fb6941b64392b51bcacc648e4da7
  experiment_id: 4
  starting_model: full_v2_e4_step1_e2.tf

# setup
scaling_cfg: ../../configs/ShuffleMergeSpectral_trainingSamples-2_files_0_498.json # for DataLoader initialisation
gpu_cfg:
  gpu_mem  : 7 # in Gb
  gpu_index: 0

# logs
log_suffix: step1
